### ISSUE TITLE
Placeholder graphics

### ISSUE THREAD

**Issue by melody-rs** [Astrabit-ST/Luminol#104]
**Is your feature request related to a problem? Please describe.**

Luminol refuses to open maps with missing assets at the moment. While this is reasonable behavior, it'd be nice if Luminol could load maps with missing assets by displaying them as placeholder graphic.

**Describe the solution you'd like**

When Luminol attempts to load missing assets, it creates a toast for every missing asset and prompts the user if they really want to open the map.

**Questions**

Should we replace any missing assets with a placeholder graphic? If so, do we create a file with the same name as the missing asset, or change the asset's path?

**Describe alternatives you've considered**

RPG Maker XP (in my experience) flat out won't complain and instead uses a blank image. This is pretty reasonable behavior too.

**Comment by white-axe** [comment]
I've never heard of programs creating missing texture files in the project. I think it would be better to just log missing textures and then use a placeholder graphic without adding files to the project. The placeholder graphic probably shouldn't be blank though, because that could be confused with actual blank parts of the map.

**Comment by melody-rs** [comment]
Mhm! I'm thinking we can use the typical black and purple square as a placeholder.
