### ISSUE TITLE
Custom egui app runner to replace eframe

### ISSUE THREAD

**Issue by melody-rs** [Astrabit-ST/Luminol#57]
**Is your feature request related to a problem? Please describe.**
eframe is nice, but is slow to update and most notably doesn't work in a web worker, so atm Luminol has a custom web runner that can't fully integrate with eframe. eframe doesn't export all the functionality required to make a custom app runner, unfortunately.

**Describe the solution you'd like**
We fork eframe and egui_wgpu and vendor our own versions of these two crates. 

**Additional context**
wgpu has just updated to 0.18 and I could see eframe and egui_wgpu taking a few more months to update. We should ideally be staying up to date with the latest wgpu release (We're currently two versions behind!!) especially since https://github.com/gfx-rs/wgpu/pull/3626 might be landing soon.

**Comment by white-axe** [comment]
Feel free to disagree, but I feel it would be beneficial to use Git subtrees for the custom eframe and egui_wgpu instead of a fork. We can subtree only the eframe and egui_wgpu directories from the upstream egui repository into the (future) crates directory in the Luminol repository, make changes to those two crates, and squash merge upstream changes at any point.

The benefits of doing this are the easier coordination and other attributes associated with a monorepo, like being able to make a single pull request that modifies both an egui crate and a Luminol crate.

The drawbacks include the slow speed of subtree merges (Git has to do a lot of calculations to rewrite the upstream commits).

**Comment by melody-rs** [comment]
That sounds perfect!
